// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCmIZFI88GfmfwkunS05Lelt6Cz1MUkqlY',
    appId: '1:1004221709686:web:d7be6a0e285b697aa6ce57',
    messagingSenderId: '1004221709686',
    projectId: 'proyecto-resendis',
    authDomain: 'proyecto-resendis.firebaseapp.com',
    storageBucket: 'proyecto-resendis.firebasestorage.app',
    measurementId: 'G-ZV9TD3JNS3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAaA_AratWkHw3tiqA-VC5JDNEveubZfMo',
    appId: '1:1004221709686:android:818f7abca7b043f6a6ce57',
    messagingSenderId: '1004221709686',
    projectId: 'proyecto-resendis',
    storageBucket: 'proyecto-resendis.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBzn85DviVHNus_hC-Rm8NIO3fSPAS9DcQ',
    appId: '1:1004221709686:ios:e5099c195c5ee005a6ce57',
    messagingSenderId: '1004221709686',
    projectId: 'proyecto-resendis',
    storageBucket: 'proyecto-resendis.firebasestorage.app',
    iosBundleId: 'com.example.projectResendis',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBzn85DviVHNus_hC-Rm8NIO3fSPAS9DcQ',
    appId: '1:1004221709686:ios:e5099c195c5ee005a6ce57',
    messagingSenderId: '1004221709686',
    projectId: 'proyecto-resendis',
    storageBucket: 'proyecto-resendis.firebasestorage.app',
    iosBundleId: 'com.example.projectResendis',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCmIZFI88GfmfwkunS05Lelt6Cz1MUkqlY',
    appId: '1:1004221709686:web:d9ecfab1bc71a66da6ce57',
    messagingSenderId: '1004221709686',
    projectId: 'proyecto-resendis',
    authDomain: 'proyecto-resendis.firebaseapp.com',
    storageBucket: 'proyecto-resendis.firebasestorage.app',
    measurementId: 'G-JX2RTSK78C',
  );
}
